
version: "3.9"
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      HOST: 0.0.0.0
    depends_on:
      - cache
      - db

  cache:
    image: "redis:alpine"
    ports:
      - 6379:6379

  ambry:
    build:
      context: .
      dockerfile: ambry-dockerfile
    ports:
      - 1174:1174
      - 1175:1175

  db:
    image: "dajobe/hbase"
    ports:
      - 32872:32872



